[theme]
base="dark"
primaryColor="#5bbf83"
backgroundColor="#333437"
secondaryBackgroundColor="#202123"


[server]
maxUploadSize = 10000


[browser]
gatherUsageStats = false


[client]
toolbarMode = "auto"

